# Generated by Django 3.0.5 on 2020-05-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_enc', models.CharField(max_length=100, verbose_name='Таблица с кодировщиком')),
                ('table_samp', models.CharField(max_length=100, verbose_name='Таблица с обучающей выборкой')),
                ('table_hyps', models.CharField(max_length=10, verbose_name='Таблица с гипотезами')),
                ('num_hyps', models.IntegerField(verbose_name='Количество гипотез')),
                ('table_test', models.CharField(max_length=100, verbose_name='Таблица с тестовой выборкой')),
                ('num_pos', models.IntegerField(verbose_name='Количество положительных примеров')),
                ('num_neg', models.IntegerField(verbose_name='Количество негативных примеров')),
            ],
            options={
                'verbose_name': 'ВКФ-эксперимент',
                'verbose_name_plural': 'ВКФ-эксперименты',
            },
        ),
    ]
