# Generated by Django 3.0.5 on 2020-05-06 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encoder', '0002_auto_20200505_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleforvkf',
            old_name='fileTRAIN_attr',
            new_name='fileSample_attr',
        ),
        migrations.RenameField(
            model_name='sampleforvkf',
            old_name='fileTRAIN_name',
            new_name='fileSample_name',
        ),
        migrations.RenameField(
            model_name='sampleforvkf',
            old_name='fileTRAIN_path',
            new_name='fileSample_path',
        ),
        migrations.RenameField(
            model_name='sampleforvkf',
            old_name='fileTRAIN_table',
            new_name='fileSample_table',
        ),
        migrations.RenameField(
            model_name='sampleforvkf',
            old_name='fileTRAIN_type',
            new_name='fileSample_type',
        ),
    ]
